name: Copy Branch from Organization Repository

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      org_name:
        description: 'Organization name'
        required: true
      org_repo:
        description: 'Organization repository name'
        required: true
      source_branch:
        description: 'Branch to copy from the organization repository'
        required: true
        default: 'main'

jobs:
  copy-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Set Git Identity
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Add remote organization repository
        run: |
          git remote add org-repo https://github.com/${{ github.event.inputs.org_name }}/${{ github.event.inputs.org_repo }}.git
          git fetch org-repo ${{ github.event.inputs.source_branch }}

      - name: Create backup branch
        run: |
          git branch backup-main-$(date +%Y%m%d%H%M%S) main
          echo "Created backup of main branch"

      - name: Reset main branch to organization's branch
        run: |
          git checkout main
          git reset --hard org-repo/${{ github.event.inputs.source_branch }}
          echo "Reset main branch to org-repo/${{ github.event.inputs.source_branch }}"

      - name: Push changes to main
        run: |
          git push origin main --force
          echo "Successfully pushed changes to main branch"
